#!/usr/bin/env bash
# Curator Agent Loop — always-on data steward
#
# Runs claude --print --session curator in a loop.
# Each iteration: check inbox, process new content, audit brains.
# Uses Sonnet for routine ingestion (cheaper, separate rate limit pool).
#
# Environment:
#   MCP_CONFIG — path to MCP config JSON (generated by entrypoint)
#   CURATOR_POLL_INTERVAL — seconds between loops (default: 60)

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_DIR"

POLL_INTERVAL="${CURATOR_POLL_INTERVAL:-60}"
MCP_CONFIG="${CURATOR_MCP_CONFIG:-${MCP_CONFIG:-/tmp/curator-mcp.json}}"
SESSION_NAME="curator"
SYSTEM_PROMPT="config/prompts/curator-system.md"
CURATOR_LOG="/tmp/curator.log"
LOOP_COUNT=0
AUDIT_EVERY=60  # Run audit every 60 loops (~1h at 60s interval)

echo "[curator] Starting curator agent loop"
echo "[curator] Poll interval: ${POLL_INTERVAL}s"
echo "[curator] MCP config: $MCP_CONFIG"
echo "[curator] System prompt: $SYSTEM_PROMPT"

while true; do
  LOOP_COUNT=$((LOOP_COUNT + 1))

  # Determine task — routine processing or periodic audit
  if [ $((LOOP_COUNT % AUDIT_EVERY)) -eq 0 ]; then
    TASK="Audit mode: pick one brain and review its facts for correctness, staleness, and misrouting. Use get_business_state to see all brains, then search_memory on the brain with the most facts. Retire anything stale, correct anything wrong, move anything misrouted. Then regenerate_brain_states."
    echo "[curator] Loop #$LOOP_COUNT — AUDIT mode"
  else
    TASK="Check get_pending_inbox for new content. If items exist: for each, read the FULL source content (entire email thread via gws gmail, complete Slack conversation via slack tools, full Fireflies transcript). Extract high-value facts and store_fact to the correct brain. Mark each inbox item as processed. If no pending items, respond with 'No pending items.' and exit."
    echo "[curator] Loop #$LOOP_COUNT — PROCESS mode"
  fi

  # Run curator session
  # --print mode: non-interactive, returns output
  # --session: maintains conversation history across invocations
  # --model: Sonnet for routine work (separate rate limit pool)
  claude --print \
    --session "$SESSION_NAME" \
    --model claude-sonnet-4-6 \
    --mcp-config "$MCP_CONFIG" \
    --append-system-prompt-file "$SYSTEM_PROMPT" \
    --dangerously-skip-permissions \
    --max-turns 50 \
    "$TASK" \
    >> "$CURATOR_LOG" 2>&1 || true

  echo "[curator] Loop #$LOOP_COUNT complete, sleeping ${POLL_INTERVAL}s"
  sleep "$POLL_INTERVAL"
done
